source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'


target 'AKAuth0TestApp' do
    pod 'Lock', '~> 1.24'
    pod 'Lock-Facebook', '~> 2.0'
    pod 'Lock-Twitter', '~> 1.1'
    pod 'Lock-Google', '~> 2.0'
    pod 'GoogleUtilities', '1.1.0'
    pod 'SimpleKeychain'
end

