platform :ios, '8.0'

target 'AKSwiftAuth0Test' do
    pod 'Lock', '~> 1.24'
    pod 'Lock-Facebook', '~> 2.0'
    pod 'Lock-Twitter', '~> 1.1'
    pod 'Lock-Google', '~> 2.0'
    pod 'GoogleUtilities', '1.1.0'
    pod 'SimpleKeychain'
end

post_install do |installer|
    installer.pods_project.build_configurations.each { |bc|
        bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    }
end